apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-for-flask-config-app
  labels:
{{ include (printf "Functions.%s.labels" (index .Values "helm-functions" "version")) (dict "chart" .Chart "values" .Values "release" .Release) | nindent 4 }}
{{- include (printf "Functions.%s.additional-labels" (index .Values "helm-functions" "version")) (dict "values" .Values)| nindent 4 }} 
data:
  secret_key: ZHNkZGZkZmRmCg==
  db_password: ZHNkZGZkZmRmCg==
