apiVersion: v1
kind: Service
metadata:
  name: {{ include (printf "Functions.%s.fullname" (index .Values "helm-functions" "version")) (dict "chart" .Chart "values" .Values "release" .Release) }}
  labels:
{{ include (printf "Functions.%s.labels" (index .Values "helm-functions" "version")) (dict "chart" .Chart "values" .Values "release" .Release) | nindent 4 }}
{{- include (printf "Functions.%s.additional-labels" (index .Values "helm-functions" "version")) (dict "values" .Values)| nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include (printf "Functions.%s.name" (index .Values "helm-functions" "version")) (dict "chart" .Chart "values" .Values) }}
    app.kubernetes.io/instance: {{ .Release.Name }}

