name: Build Docker Image on Demand

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --progress=plain \
            --tag my-app:latest \
            --tag my-app:${{ github.sha }} \
            ./app
